### ISSUE TITLE
Show image based on template argument

### ISSUE THREAD

**Issue by flaviojs** [bwanders/dokuwiki-plugin-templatery#3]
I want to show an image in a template based on a template argument.

1) Sending the image as an argument does not work:
```
{{template>monster#page|id=1|name=Monster|image={{monster.png}}|etc=...}}
```

2) Building the image in the template also does not work:
```
{{template>monster#page|id=1|name=Monster|image=monster.png|etc=...}}

<template page>
{{@@image@@}}
</template>
```

**Comment by flaviojs** [comment]
I can see why 1) doesn't work after reading https://www.dokuwiki.org/devel:parser

I was expecting `@@args@@` to be replaced as `{{template>monster#page|...}}` is being replaced, before the replacement is lexed, but considering 2) that isn't the case.

---

I'll probably have to write a syntax plugin, and if possible I'd like to change how templatery shows it in the template page. Can you give me a minimal example of what I need to do?

**Comment by bwanders** [comment]
Depending on how much "low level" control you want over the exact display of the image, there's two ways to go about this. The first is to use another two plugins of mine that together match the scenario you describe; the second option would be indeed to create a syntax plugin.

I would suggest looking at the first method to see if that solves your problem. If it does, you'll get some additional features out of the box. If you still want to write a syntax plugin, I have written some pointers there to get you started.

Let me know how this worked out for you!

Use strata & stratatemplatery
-----------------------------

The first method is to use [stratatemplatery](https://github.com/bwanders/dokuwiki-plugin-stratatemplatery) (which depends on the [strata](https://github.com/bwanders/dokuwiki-strata) plugin).

Stratetemplatery is a plugin that combines the template abilities from the [templatery](https://github.com/bwanders/dokuwiki-plugin-templatery) plugin with the data capabilities of the [strata](https://github.com/bwanders/dokuwiki-strata) plugin.

Even without modelling your monster data as actual data, that would allow you to do the following:

```
<template page>
@@name@@ (@@id@@)
@@image[image]@@
</template>
```
And invoke it with:
```
{{template>monster#page|id=1|name=Monster|image=monster.png|etc=...}}
```

Note that the `image` variable is given a type hint with `[image]`, which indicates to templatery that image type rendering should be applied. Other types will also be available to you, as listed on https://www.dokuwiki.org/plugin:strata#types.

Of course, if you are using Strata anyway, you could just as well decide to go the distance and make your monster data more listable and queryable.

Create custom syntax
--------------------

The second option is indeed to write a custom syntax plugin. I currently do not have the time to produce a minimal example, but I can point you in the right way.

The easiest way to go about making additional "template aware" syntax is to subclass from `syntax_plugin_templatery_native` (defined in https://github.com/bwanders/dokuwiki-plugin-templatery/blob/master/syntax/native.php). This helps to more easily determine whether you are in preview mode (showing the template itself) or in actual mode (rendering the template).

This utility class is itself a syntax plugin so the normal syntax plugin methods and configuration still works.

If you want to adhere to the basic Dokuwiki image syntax you'll have to override the native image pattern with your own syntax plugin, which works in a similar manner to how I override the native header pattern in https://github.com/bwanders/dokuwiki-plugin-templatery/blob/master/syntax/header.php.

**Comment by flaviojs** [comment]
Unfortunately strata is not an option for me but thanks to your info I was able to think of lots of ways I could implement this, thanks. :)

It's a 1-to-1 replacement, so I chose to specialize `@@field|default@@` for media like this (with a plugin):
```
@@media>field|default@@
```
I wanted to do the replacement during the lexer stage, but you're caching template instructions so that is a no-go. Instead I'm using `Doku_Handler_Parse_Media` during the real render, which is probably ok since there is page cache.

**Comment by bwanders** [comment]
You are correct, the whole idea of the templatery plugin is to not do string manipulation before/during the lexing stage. The reason for this is that mutating the source before lexing, while more powerful, is also more fragile, leading to very strange things. For example, things like `{{template>test|foo=bar[[|baz=]]quux}}`.

If using `Doku_Handler_Parse_Media` during the real render works for you because most of your pages are cached, that's a good method.

If, for some reason, that does not work out or you want better control over how the image is displayed, you can also have a look at using the `internalmedia` rendered method (https://xref.dokuwiki.org/reference/dokuwiki/nav.html?_functions/internalmedia.html). Note that the media id needs to be resolved before passing it to that function, which is easily done with `resolve_mediaid` (https://xref.dokuwiki.org/reference/dokuwiki/nav.html?inc/pageutils.php.source.html#l496).

I'm closing this issue for now, as it seems that you have found a working solution. If not, do not hesitate to reopen.
