### ISSUE TITLE
Inline template

### ISSUE THREAD

**Issue by flaviojs** [bwanders/dokuwiki-plugin-templatery#4]
I'd like to be able to use a template in the middle of text (inline instead of block).

Inspired by your recursion example and `<*if>`, here is a possibility:
```
The first three Greek letters are named {{*template>list#inline|Alpha|Beta|Gamma}}.
```
Template section:
```
<template inline>@@0@@<*if 1>, <*if !2>and </if>{{*template>list#inline|0=1|1=2|2=3|3=4}}</if></template>
```
Expected result:
```
The first three Greek letters are named Alpha, Beta, and Gamma.
```

PS- Without reading the docs I would expect `{{template>` and `<if>` to be inline by default. The user can easily create blocks by adding newlines, while undoing the start of a block is impossible.

**Comment by bwanders** [comment]
The tricky part with this is that dokuwiki does a lot of things to ensure that it produces valid HTML. This includes more complex block handling than you would expect at first.

The reason that `{{template>` is not inline by default is that there is no guarantee that the included template is actually a valid inline template. If it is not a valid inline template, that would break dokuwiki's careful block handling.

A special syntax as you suggested could work, given that the included template is carefully analyzed and "de-blocked". I'm open to Pull Requests, but don't have the time to work on something like that myself.

(Quik edit: On a positive note, https://github.com/bwanders/dokuwiki-plugin-stratatemplatery/blob/master/syntax/listview.php already roughly shows how to analyse and slice a template. You'd need to make sure that the template content you are including is actually inline-only, one way of doing that is to pick up only the contents of the first paragraph.)
