### ISSUE TITLE
Does not install or run on Release rc-2020-06-09 "Hogfather" RC3

### ISSUE THREAD

**Issue by pop-ch** [bwanders/dokuwiki-plugin-templatery#5]
PHP Version 5.6.40

A manual install of the templatery on dokuwiki Release rc-2020-06-09 "Hogfather" RC3 using the extension manager bricks the wiki. No pages at all can be shown. The error message is

Fatal error: Interface 'Doku_Handler_CallWriter_Interface' not found in /volume1/web/dokuwiki/lib/plugins/templatery/syntax/conditional.php on line 106

After  moving the plugin manually into dokuwiki/lib/plugins/templatery the wiki shows the :start page and little else. The error message is the same as above.
Removing the file conditional.php (I know that this is not a solution) has little effect. The :start page is shown and little else. The error message reads this time:
Fatal error: Interface 'Doku_Handler_CallWriter_Interface' not found in /volume1/web/dokuwiki/lib/plugins/templatery/syntax/inlineconditional.php on line 107

**Comment by bwanders** [comment]
Ouch, that's a disappointing lack of compatibilty. Thanks for reporting!

**Comment by bwanders** [comment]
The codebase has been adjusted for the Hogfather refactor.

It no longer works on Greebo and earlier, but should work for Hogfather (and hopefully future releases as well).
